Pandas

In [3]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\acer\desktop\python apr 10\pandas\env\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\acer\desktop\python apr 10\pandas\env\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\acer\desktop\python apr 10\pandas\env\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\acer\desktop\python apr 10\pandas\env\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\acer\desktop\python apr 10\pandas\env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import pandas as pd

In [9]:
# creating series from list
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [12]:
#custom index
marks = pd.Series([90, 80, 70], index= ['maths', 'science', 'english'])
marks

maths      90
science    80
english    70
dtype: int64

In [22]:
print(marks['maths'])

90

In [24]:
#creating series from dictionary
data_dict= {'a':1, 'b':2, 'c': 3}
series_dict = pd.Series(data_dict)
series_dict

a    1
b    2
c    3
dtype: int64

In [46]:
#creating scalar data -- sabbai data lai eutai value indicate garna lai
series = pd.Series(5, index=['Ram', 'Shyam', 'Gita'])
series

Ram      5
Shyam    5
Gita     5
dtype: int64

In [47]:
#Accesing series data
marks = pd.Series([80,85,90], index= ['Ram', 'Shyam', 'Gita'])
print (marks.iloc[0])  #iloc le chai position use garna lai
print (marks['Gita'])

80
90

In [51]:
# Series Real Example
stock_prices = pd.Series([157,156,142,124,667], index=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'])
print(stock_prices.iloc[1])
print(stock_prices['Tuesday'])

156
156

In [57]:
print(stock_prices.mean())
print(stock_prices.max())
print(stock_prices.min())
print(stock_prices[stock_prices > 150])

249.2
667
124
Monday     157
Tuesday    156
Friday     667
dtype: int64

Data Frame with two- dimensional data with rows and columns.

In [59]:
data = {
    'Name' : ['Alice', 'Bob', 'Charlie'],
    'Age' : [25, 30, 35],
    'City' : ['Kathmandu', 'Bhaktapur', 'Lalitpur']
}

df = pd.DataFrame(data)
print(df)

      Name  Age       City
0    Alice   25  Kathmandu
1      Bob   30  Bhaktapur
2  Charlie   35   Lalitpur

In [69]:
df.head(2) #First dekhi ko data

    Name  Age       City
0  Alice   25  Kathmandu
1    Bob   30  Bhaktapur

In [68]:
df.tail(1) #Last dekhi ko data

      Name  Age      City
2  Charlie   35  Lalitpur

In [70]:
df.shape #rows and columns

(3, 3)

In [77]:
#Columns name
df.columns

Index(['Name', 'Age', 'City'], dtype='str')

In [79]:
df.dtypes

Name      str
Age     int64
City      str
dtype: object

In [82]:
df.describe() #summary nikalxa numerical data ko matra

        Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

In [84]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   City    3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [97]:
print(df['Name'])
print (df[['Name','City']])

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str
      Name       City
0    Alice  Kathmandu
1      Bob  Bhaktapur
2  Charlie   Lalitpur

In [102]:
#access by position rowwise
df.iloc[0]

Name        Alice
Age            25
City    Kathmandu
Name: 0, dtype: object

In [114]:
#filtering dataframe
#And condition
filtered_df = df[(df['Age'] > 28) & (df['City'] == 'Bhaktapur')]
filtered_df

  Name  Age       City
1  Bob   30  Bhaktapur

In [117]:
#Or condition
filtered_df = df[(df['Age'] > 28) | (df['City'] == 'Bhaktapur')]
filtered_df

      Name  Age       City
1      Bob   30  Bhaktapur
2  Charlie   35   Lalitpur

In [119]:
# Crud Add,Update, Delete
# Adding a new column
df['Salary'] = [50000, 60000, 70000]
print(df)

      Name  Age       City  Salary
0    Alice   25  Kathmandu   50000
1      Bob   30  Bhaktapur   60000
2  Charlie   35   Lalitpur   70000

In [121]:
#Updating existing column with condition
df.loc[df['Age']> 30, 'Salary'] = df['Salary'] + 10000
df

      Name  Age       City  Salary
0    Alice   25  Kathmandu   50000
1      Bob   30  Bhaktapur   60000
2  Charlie   35   Lalitpur   90000

In [131]:
#Deleting a column
 
df.drop('Salary', axis=1, inplace=True)
print(df)

KeyError: "['Salary'] not found in axis"

In [130]:
#Deleting a row
df.drop(0, axis=0, inplace=True)
df

      Name  Age       City
1      Bob   30  Bhaktapur
2  Charlie   35   Lalitpur

In [133]:
#Read CSV filter
df = pd.read_csv('sample_users_e60d27fb-7f72-4292-9470-260e6037135e.csv')

In [135]:
df.shape

(500, 12)

In [137]:
df.head()

,first_name,last_name,company_name,address,city,county,state,zip,phone1,phone2,email,web
0,James,Butt,"Benton, John B Jr",6649 N Blue Gum St,NaN,Orleans,LA,70116,504-621-8927,504-845-1427,jbutt@gmail.com,http://www.bentonjohnbjr.com
1,Josephine,Darakjy,"Chanay, Jeffrey A Esq",4 B Blue Ridge Blvd,Brighton,Livingston,MI,48116,810-292-9388,810-374-9840,josephine_darakjy@darakjy.org,http://www.chanayjeffreyaesq.com
2,Art,Venere,"Chemel, James L Cpa",8 W Cerritos Ave #54,Bridgeport,Gloucester,NJ,8014,856-636-8749,856-264-4130,art@venere.org,http://www.chemeljameslcpa.com
3,Lenna,Paprocki,Feltz Printing Service,639 Main St,Anchorage,Anchorage,AK,99501,907-385-4412,907-921-2010,lpaprocki@hotmail.com,http://www.feltzprintingservice.com
4,Donette,Foller,Printing Dimensions,34 Center St,Hamilton,Butler,OH,45011,513-570-1893,513-549-4561,donette.foller@cox.net,http://www.printingdimensions.com

In [138]:
df.tail()

,first_name,last_name,company_name,address,city,county,state,zip,phone1,phone2,email,web
495,Brittni,Gillaspie,Inner Label,67 Rv Cent,Boise,Ada,ID,83709,208-709-1235,208-206-9848,bgillaspie@gillaspie.com,http://www.innerlabel.com
496,Raylene,Kampa,Hermar Inc,2 Sw Nyberg Rd,Elkhart,Elkhart,IN,46514,574-499-1454,574-330-1884,rkampa@kampa.org,http://www.hermarinc.com
497,Flo,Bookamer,Simonton Howe & Schneider Pc,89992 E 15th St,Alliance,Box Butte,NE,69301,308-726-2182,308-250-6987,flo.bookamer@cox.net,http://www.simontonhoweschneiderpc.com
498,Jani,Biddy,Warehouse Office & Paper Prod,61556 W 20th Ave,Seattle,King,WA,98104,206-711-6498,206-395-6284,jbiddy@yahoo.com,http://www.warehouseofficepaperprod.com
499,Chauncey,Motley,Affiliated With Travelodge,63 E Aurora Dr,Orlando,Orange,FL,32804,407-413-4842,407-557-8857,chauncey_motley@aol.com,http://www.affiliatedwithtravelodge.com

In [3]:
!pip install matplotlib

Requirement already satisfied: matplotlib in c:\users\acer\desktop\python apr 10\pandas\env\lib\site-packages (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\acer\desktop\python apr 10\pandas\env\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\acer\desktop\python apr 10\pandas\env\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\acer\desktop\python apr 10\pandas\env\lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\acer\desktop\python apr 10\pandas\env\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in c:\users\acer\desktop\python apr 10\pandas\env\lib\site-packages (from matplotlib) (2.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\acer\desktop\python apr 10\pandas\env\lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in c:\users\acer\desktop\python apr 10\pandas\env\lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\acer\desktop\python apr 10\pandas\env\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\acer\desktop\python apr 10\pandas\env\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\acer\desktop\python apr 10\pandas\env\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip